Update docs for `secretsMap` option support
streamnative/function-mesh-website pull request #114
Opened 2022-03-22 08:21 UTC by Huanli-Meng

### Motivation
In Function Mesh V0.1.9 release, [secrets are supported](https://github.com/streamnative/function-mesh-worker-service/pull/21). Therefore, update docs for this code PR.

### Modifications:
- Update docs for secrets supported on function mesh worker service.
  - Related release: latest
- Refine authentication descriptions 
  - Related releases: v0.1.5- latest
- Update typos, code format and heading levels:
  - Related releases: all releases

2022-03-25 08:05 UTC, freeznet reviewed
please check my comment, I only made suggestions on sink doc and the changes can be used for source and function as well because the content of sink, source and function should be similar.

2022-03-25 08:05 UTC, freeznet commented on docs/connectors/io-crd-config/sink-crd-config.md
> +This table lists configurations about the `SecretsMap` field.
`SecretsMap` is defined as a `Map` struct with `String` keys and `SecretReference` values. The `key` will indicate the environment value in the container, and the `SecretReference` is defined as below.

| Field | Description |
 | --- | --- |
 | `path` | The name of the secret in the pod's namespace to select from. |
 | `key` | The key of the secret to select from.  Must be a valid secret key. |

For example, the user has a Kubernetes Secret named `credential-secret` defined as below:

```yaml
 apiVersion: v1
 data:
   username: foo
   password: bar
 kind: Secret
 metadata:
   name: credential-secret
 type: Opaque
 ```

To use it in Pulsar Functions in a security way, simply define the `SecretsMap` in the Custom Resource:

```
secretsMap:
  username:
    path: credential-secret
    key: username
  password:
    path: credential-secret
    key: password
```

Then in the Pulsar Functions and Connectors, you can call `context.getSecret("username")` to get the secret value.

2022-03-28 03:07 UTC, Huanli-Meng commented
@freeznet Thanks for your valuable comments. Docs have been updated based on you comments. PTAL again and feel free to approve it if there is no more comment. Thanks.

2022-03-28 06:02 UTC, freeznet reviewed
sorry, i have made some minor changes, to fix the wrong resouce ref in the custom resource.

2022-03-28 06:02 UTC, freeznet commented on docs/connectors/io-crd-config/sink-crd-config.md
> +    key: foo
```suggestion
    key: username
```

2022-03-28 06:02 UTC, freeznet commented on docs/connectors/io-crd-config/sink-crd-config.md
> +    key: bar
```suggestion
    key: password
```

2022-03-28 06:02 UTC, freeznet commented on docs/connectors/io-crd-config/sink-crd-config.md
> +Then, in the Pulsar Functions and Connectors, you can call `context.getSecret("username")` to get the secret value.
```suggestion
Then, in the Pulsar Functions and Connectors, you can call `context.getSecret("username")` to get the secret value `"foo"`.
```

2022-03-28 06:37 UTC, Huanli-Meng commented
> sorry, i have made some minor changes, to fix the wrong resouce ref in the custom resource.

It's OK. I have updated the doc based on your comments. PTAL again. Thanks

2022-03-28 06:46 UTC, freeznet approved these changes
thanks, lgtm

2022-03-30 20:26 UTC, teachwrite requested changes
These are all small changes, and many are changes to the same sentence repeated through the documents. After you make these changes, you can go ahead and merge this PR.

2022-03-30 20:26 UTC, teachwrite commented on docs/connectors/io-crd-config/sink-crd-config.md
> +Function Mesh provides the `SecretsMap` field for Function, Source and Sink in the CRD definition. You can refer to the created secrets under the same namespace and the controller can include those r
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..") and a comma before which in the last sentence "... `EnvironmentBasedSecretsProvider`, which..."

2022-03-30 20:26 UTC, teachwrite commented on docs/connectors/io-crd-config/sink-crd-config.md
> +To use it in Pulsar Functions in a security way, you can define the `SecretsMap` in the Custom Resource:
"in a secure way"

2022-03-30 20:26 UTC, teachwrite commented on docs/connectors/io-crd-config/sink-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on docs/connectors/io-crd-config/source-crd-config.md
> +Function Mesh provides the `SecretsMap` field for Function, Source and Sink in the CRD definition. You can refer to the created secrets under the same namespace and the controller can include those r
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..") and a comma before which in the last sentence "... EnvironmentBasedSecretsProvider, which..."

2022-03-30 20:26 UTC, teachwrite commented on docs/connectors/io-crd-config/source-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on docs/functions/function-crd.md
> +Function Mesh provides the `SecretsMap` field for Function, Source and Sink in the CRD definition. You can refer to the created secrets under the same namespace and the controller can include those r
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..") and a comma before which in the last sentence "... EnvironmentBasedSecretsProvider, which..."

2022-03-30 20:26 UTC, teachwrite commented on docs/functions/function-crd.md
> +To use it in Pulsar Functions in a security way, you can define the `SecretsMap` in the Custom Resource:
"in a secure way"

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.5/connectors/io-crd-config/sink-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.5/connectors/io-crd-config/source-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.5/functions/function-crd.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.6/connectors/io-crd-config/sink-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.6/connectors/io-crd-config/source-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.6/functions/function-crd.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.7/connectors/io-crd-config/sink-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.7/connectors/io-crd-config/source-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.7/functions/function-crd.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.7/scaling.md
> +  This table lists built-in memory-based autoscaling metrics. If these metrics cannot meet your requirements, you can auto-scale the number of Pods based on customized metrics defined in Pulsar Funct
"If these metrics do not meet..."

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.8/connectors/io-crd-config/sink-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.8/connectors/io-crd-config/source-crd-config.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.8/functions/function-crd.md
> +Function Mesh provides the `TLSSecret` and `AuthSecret` fields for Function, Source and Sink in the CRD definition. You can configure TLS encryption and/or TLS authentication using the following conf
need a comma after "Source" in the first sentence ("...Function, Source, and Sink..")

2022-03-30 20:26 UTC, teachwrite commented on versioned_docs/version-0.1.8/scaling.md
> +  This table lists built-in memory-based autoscaling metrics. If these metrics cannot meet your requirements, you can auto-scale the number of Pods based on customized metrics defined in Pulsar Funct
"If these metrics do not meet..."

2022-03-31 03:28 UTC, Huanli-Meng commented
@teachwrite , I have applied your comments into docs. PTAL again. If you choose "Change request" when you submit your comments, i cannot merge the PR directly. Thanks.

2022-04-02 01:18 UTC, merged