[v0.1.11]--Add function mesh worker service config
streamnative/function-mesh-website pull request #120
Opened 2022-04-07 08:19 UTC by Huanli-Meng

### Motivation

This PR is to update docs for [code PR --support custom labels and annotations in custom config](https://github.com/streamnative/function-mesh-worker-service/pull/84).

### Modification
- Update Function Mesh Worker service config

2022-04-07 10:03 UTC, freeznet approved these changes

2022-04-08 17:02 UTC, teachwrite requested changes
Just a few small changes needed.

2022-04-08 17:02 UTC, teachwrite commented on docs/function-mesh-worker/deploy-mesh-worker.md
> +| `functionLabels` | Map < String, String > | No | {} (empty string) | Specify the labels being attach to a Function's Pod. When both `functionLabels` and `labels` are specified, `functionLabels` ove
```suggestion
| `functionLabels` | Map < String, String > | No | {} (empty string) | Specify the labels being attached to a Function's Pod. When both `functionLabels` and `labels` are specified, `functionLabels` overrides `labels`. |
```

2022-04-08 17:02 UTC, teachwrite commented on docs/function-mesh-worker/deploy-mesh-worker.md
> +| `sinkLabels` | Map < String, String > | No | {} (empty string) | Specify the labels being attach to a Sink's Pod. When both `sinkLabels` and `labels` are specified, `sinkLabels` overrides `labels`.
```suggestion
| `sinkLabels` | Map < String, String > | No | {} (empty string) | Specify the labels being attached to a Sink's Pod. When both `sinkLabels` and `labels` are specified, `sinkLabels` overrides `labels`. |
```

2022-04-08 17:02 UTC, teachwrite commented on docs/function-mesh-worker/deploy-mesh-worker.md
> +| `sourceLabels` | Map < String, String > | No | {} (empty string) | Specify the labels being attach to a Source's Pod. When both `sourceLabels` and `labels` are specified, `sourceLabels` overrides `
```suggestion
| `sourceLabels` | Map < String, String > | No | {} (empty string) | Specify the labels being attached to a Source's Pod. When both `sourceLabels` and `labels` are specified, `sourceLabels` overrides `labels`. |
```

2022-04-08 17:02 UTC, teachwrite commented on docs/function-mesh-worker/deploy-mesh-worker.md
> +| `functionAnnotations` | Map < String, String > | No | {} (empty string) | Specify the annotations being attach to a Function's Pod. When both `functionAnnotations` and `annotations` are specified,
```suggestion
| `functionAnnotations` | Map < String, String > | No | {} (empty string) | Specify the annotations being attached to a Function's Pod. When both `functionAnnotations` and `annotations` are specified, `functionAnnotations` overrides `annotations`. |
```

2022-04-08 17:02 UTC, teachwrite commented on docs/function-mesh-worker/deploy-mesh-worker.md
> +| `sinkAnnotations` | Map < String, String > | No | {} (empty string) | Specify the annotations being attach to a Sink's Pod. When both `sinkAnnotations` and `annotations` are specified, `sinkAnnotat
```suggestion
| `sinkAnnotations` | Map < String, String > | No | {} (empty string) | Specify the annotations being attached to a Sink's Pod. When both `sinkAnnotations` and `annotations` are specified, `sinkAnnotations` overrides `annotations`. |
```

2022-04-08 17:02 UTC, teachwrite commented on docs/function-mesh-worker/deploy-mesh-worker.md
> +| `sourceAnnotations` | Map < String, String > | No | {} (empty string) | Specify the annotations being attach to a Source's Pod. When both `sourceAnnotations` and `annotations` are specified, `sourc
```suggestion
| `sourceAnnotations` | Map < String, String > | No | {} (empty string) | Specify the annotations being attached to a Source's Pod. When both `sourceAnnotations` and `annotations` are specified, `sourceAnnotations` overrides `annotations`. |
```

2022-04-11 01:51 UTC, Huanli-Meng commented
@teachwrite Thanks for your comments. I have applied all your comments. Could you please have another look in to it and feel free to approve it if there is no more comment. Thanks.

2022-04-11 11:41 UTC, teachwrite approved these changes
LGTM

2022-04-11 12:48 UTC, merged