[FM v0.10.0]--Add doc release note
streamnative/function-mesh-website pull request #232
Opened 2023-01-18 04:14 UTC by Huanli-Meng

### Motivation

Add a doc release note for Function Mesh v0.10.0 ([code PR #560](https://github.com/streamnative/function-mesh/pull/560/)).

### Modification
- Add Release note v0.10.0
- Update the `sidebar.json` file
- Update the **Overview** document

2023-01-18 13:34 UTC, tpiperatgod requested changes

2023-01-18 13:34 UTC, tpiperatgod commented on docs/overview/overview.md
> +  - [Release notes v0.9.0](/releases/release-note-0-10-0.md)
"Release notes v0.9.0" => "Release notes v0.10.0"

2023-01-18 13:34 UTC, tpiperatgod commented on docs/releases/release-note-0-10-0.md
> +In previous releases, if a function package uses the HTTP or HTTPS protocol, you cannot download the function package directly if you do not have an `admin` access right. In this release, Function Me
"if you enable the enable the"

2023-01-18 23:37 UTC, teachwrite approved these changes
LGTM

2023-01-18 23:37 UTC, teachwrite commented on docs/releases/release-note-0-10-0.md
> +Function Mesh supports Kubernetes [Horizontal Pod Autoscaler (HPA)](https://kubernetes.io/docs/tasks/run-application/horizontal-Pod-autoscale/) and [Vertical Pod Autoscaler (VPA)](https://github.com/
```suggestion
Function Mesh supports Kubernetes [Horizontal Pod Autoscaler (HPA)](https://kubernetes.io/docs/tasks/run-application/horizontal-Pod-autoscale/) and [Vertical Pod Autoscaler (VPA)](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) to automatically adjust capacity of your Pods to maintain steady, predictable performance at the lowest possible cost. In this release, the Function Mesh Worker service also supports HPA and VPA specifications. For details, see [customizable options](/function-mesh-worker/reference/customizable-option.md).
```

2023-01-18 23:37 UTC, teachwrite commented on docs/releases/release-note-0-10-0.md
> +In previous releases, if a function package uses the HTTP or HTTPS protocol, you cannot download the function package directly if you do not have an `admin` access right. In this release, Function Me
Also, no "an" before "admin".

2023-01-19 03:35 UTC, Huanli-Meng commented
@tpiperatgod Thanks for your comments. Docs are updated accordingly. PTAL again. Thanks.

2023-01-19 03:46 UTC, tpiperatgod approved these changes
lgtm

2023-01-19 06:51 UTC, merged