Re-add the version control script
streamnative/function-mesh-website pull request #66
Opened 2021-05-05 18:20 UTC by zeo1995

Re-add the version control script

2021-05-07 00:41 UTC, Huanli-Meng requested changes
The `docs/overview.md` should not be covered in this PR. And i cannot access to the preview link of the function mesh website.

2021-05-07 02:39 UTC, tuteng commented on replace.js
> +      console.log(changes)
Delete this debug

2021-05-10 03:03 UTC, tuteng commented
ping @Huanli-Meng PTAL

2021-05-10 06:10 UTC, Huanli-Meng approved these changes

2021-05-10 06:10 UTC, Huanli-Meng commented
> ping @Huanli-Meng PTAL

approved

2021-05-10 12:02 UTC, tuteng approved these changes

2021-05-10 12:02 UTC, merged